select *
from customer
limit 20,

-- Total revenue generated by male and female customers
select gender, sum(purchase_amount)
from customer
group by gender;

-- which customers used a discount but still spend more than the average puchase amount
select customer_id, discount_applied, purchase
from customer
where discount_applied = 'Yes' and purchase_amount >
(select avg(purchase_amount)
from customer);

-- top 5 product with highest average review rating
select item_purchased, round(avg(review_rating::numeric), 2) as review
from customer
group by item_purchased
order by review desc
limit 5;

-- average puchase amounts between standard and express shipping
select shipping_type, round(avg(purchase_amount), 2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;


-- average spending and total revenue between subscribers and non subscribers customer
select subscription_status, count(customer_id) as total_customers, 
round(avg(purchase_amount), 2) as avg_spend, round(sum(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


-- top 5 producst with the highes percentage of puchases with discounts applied
select item_purchased, round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*), 2) as total_purchased
from customer
group by item_purchased
order by total_purchased desc
limit 5;

-- segment customers into New, Returning and loyal based on their total 
-- number of previours purchases, and show the count of each segment (1: new, 2-10: returning, more than 10: loyal)

with  customer_type as(
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment, count(previous_purchases) as  "Number of Customer"
from customer_type
group by customer_segment;


-- what are the top three most puchased product in each category

with item_count as(
select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <=3;

-- are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe
-- the subscription offer is not attrictive to the customer
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- what is the revenue contributed of each age group
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;



